### ISSUE TITLE
Compatibility with 78+

### ISSUE THREAD

**Issue by stef204** [revad/limit_non-BCC_recipients#2]
This does not seem to have the option of replacing `To` with `BCC` like the previous version had.
Any plans for that?

**Comment by revad** [comment]
If this issue is about compatibility with 78+ - which is the issue title - it is.

If you're referring to the option available with the addon 'Use BCC Instead', then no - I have no plans to do that.

It currently cannot be done with a pure Mail Extension anyway. If an API became available that could do it it would be better done as a separate addon, IMO, rather that adding lots of BCC-related functions into this one. It would presumably be pretty simple - no options required for example.

**Comment by stef204** [comment]
sorry, I initially was looking at your other BCC extension and then found this one which as you have said, is compatible.

I do not have the ability to modify the title of the ticket unfortunately. But you probably do, feel free.

The feature to use BCC instead of To, by default, can be extremely useful, depending on one's work flow, etc.  The legacy extension did offer it, which led me here.

Thanks for your reply.  If at some point you are able to address that feature, would be appreciated probably by many users.

**Comment by revad** [comment]
I can't change the title either. I'll close this.

As you may know, I didn't write 'Use BCC Instead' - only made a version for TB60+ because the original author wouldn't. I never used the feature to default To to BCC on the compose window. With this new addon you can of course set the maximum number of non-BCC users to zero which pretty much ensures you don't send anything accidentally.
